development:
  adapter: postgresql
  encoding: unicode
  database: customerbora_development
  pool: 25
  username: Jose
  password: "4114"
  template: template0
  host: localhost

test: &test
  adapter: postgresql
  encoding: unicode
  database: customerbora_test
  pool: 25
  username: Jose
  password: "4114"
  template: template0
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: customerbora_development
  pool: 25
  username: jose
  password: "4114"
  template: template0
  host: localhost

